# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Detectree docker CI test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04
    container: ma595/detectree-cpu-all:latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    # - name: Install detectree2
    #   run: |
    #     pip install .
    - name: flake8 checks
      continue-on-error: true
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 detectree2 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        flake8 detectree2 --count --max-complexity=10 --statistics
    - name: wget
      uses: wei/wget@v1 
      with:
        args: https://zenodo.org/record/5515408/files/RCD105_MA14_21_orthomosaic_20141023_reprojected_full_res.tif?download=1
    - name: pytest checks
      run: |
        # pytest
        python -m pytest -rP -v detectree2/tests/test_preprocessing.py 
    - name: mypy checks
      run: |
        mypy detectree2
    - name: isort checks
      run: |
        isort --check detectree2