# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Detectree docker CI test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container: ma595/detectree-cpu-dev:latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install detectree2
      run: |
        git clone git@github.com:PatBall1/detectree2.git
        cd detectree2
        pip install .
    - name: flake8 checks
      continue-on-error: true
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 detectree2 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        flake8 detectree2 --count --max-complexity=10 --statistics
    - name: pytest checks
      run: |
        pytest
    - name: mypy checks
      run: |
        mypy detectree2
    - name: isort checks
      run: |
        isort --check detectree2